CryptoLibrary.CryptoLibraryClass Class Reference
Class for file transformation operations.
Public Member Functions
CryptoLibraryClass (byte[] key)
Initializes a new instance of the CryptoTrailClass class with the specified key.
int TransformFile (string sourceFilePath, string destFilePath, int operation)
Transforms a file based on the specified operation.
int HOTP (byte[] key, int counter)
Calculates the HOTP (HMAC-based One-Time Password) value based on the specified key and counter.
byte[] ComputeSHA1 (byte[] data)
Computes the SHA-1 hash of the given data.
byte[] ComputeHMACSHA1 (byte[] data, byte[] key)
Computes the HMAC-SHA1 hash of the given data using the provided key.
byte[] ComputeSHA256 (byte[] data)
Computes the SHA-256 hash of the given data.
bool CompareHashes (byte[] hash1, byte[] hash2)
Compares two hash values for equality.
byte[] EncryptData (byte[] data)
Encrypts the data using AES encryption.
byte[] DecryptData (byte[] data)
Decrypts the data using AES decryption.
string ByteArrayToHex (byte[] bytes)
Converts a byte array to a hexadecimal string.
Private Member Functions
int CalculateDynamicTruncation (byte[] hmacBytes)
Calculates the dynamic truncation value based on the provided HMAC-SHA1 hash.
void ConvertToBinary (string inputFile, string outputFile)
Converts the contents of the input file to binary and saves it to the output file.
byte[] CreateBuffer (byte[] sha1D, byte[] fileData, byte[] sha256D)
Creates a buffer by combining the SHA1 digest, file data, and SHA256 digest.
int GetPasswordFromDigest (byte[] digest)
Gets the password from the SHA256 digest.
Private Attributes
readonly byte[] key
The encryption key.
Static Private Attributes
const int KeySizeInBytes = 16
The size of the encryption key in bytes.
const int BlockSizeInBytes = 16
The size of the encryption block in bytes.
Detailed Description
Class for file transformation operations.
Definition at line 8 of file CryptoLibrary.cs.
Constructor & Destructor Documentation
CryptoLibraryClass()
CryptoLibrary.CryptoLibraryClass.CryptoLibraryClass (byte[] key)
Initializes a new instance of the CryptoTrailClass class with the specified key.
Parameters
key The encryption key.
Exceptions
ArgumentException Thrown when the key size is not equal to KeySizeInBytes.
Definition at line 26 of file CryptoLibrary.cs.
                                        {
    if (key.Length != KeySizeInBytes) {
      throw new ArgumentException($"Key size must be {KeySizeInBytes} bytes.");
    }
    this.key = new byte[key.Length];
    Array.Copy(key, this.key, key.Length);
  }
References CryptoLibrary.CryptoLibraryClass.key, and CryptoLibrary.CryptoLibraryClass.KeySizeInBytes.
Referenced by CryptoLibrary.CryptoLibraryClass.HOTP(), and CryptoLibrary.CryptoLibraryClass.TransformFile().
Member Function Documentation
ByteArrayToHex()
string CryptoLibrary.CryptoLibraryClass.ByteArrayToHex (byte[] bytes)
Converts a byte array to a hexadecimal string.
Parameters
bytes The byte array to convert.
Returns
The hexadecimal representation of the byte array.
Definition at line 234 of file CryptoLibrary.cs.
                                             {
    StringBuilder hex = new StringBuilder(bytes.Length * 2);
    foreach (byte b in bytes)
      hex.AppendFormat("{0:x2}", b);
    return hex.ToString();
  }
CalculateDynamicTruncation()
int CryptoLibrary.CryptoLibraryClass.CalculateDynamicTruncation (byte[] hmacBytes) [private]
Calculates the dynamic truncation value based on the provided HMAC-SHA1 hash.
Parameters
hmacBytes The HMAC-SHA1 hash as a byte array.
Returns
The dynamic truncation value as an unsigned integer.
Definition at line 100 of file CryptoLibrary.cs.
                                                           {
    int offset = hmacBytes[19] & 0xf;
    int bin_code = ((hmacBytes[offset] & 0x7f) << 24)
                   | ((hmacBytes[offset + 1] & 0xff) << 16)
                   | ((hmacBytes[offset + 2] & 0xff) << 8)
                   | (hmacBytes[offset + 3] & 0xff);
    return bin_code;
  }
Referenced by CryptoLibrary.CryptoLibraryClass.HOTP().
CompareHashes()
bool CryptoLibrary.CryptoLibraryClass.CompareHashes (byte[] hash1, byte[] hash2)
Compares two hash values for equality.
Parameters
hash1 The first hash value as a byte array.
hash2 The second hash value as a byte array.
Returns
True if the hash values are equal, otherwise false.
Definition at line 145 of file CryptoLibrary.cs.
                                                        {
    if (hash1.Length != hash2.Length) {
      return false;
    }
    for (int i = 0; i < hash1.Length; i++) {
      if (hash1[i] != hash2[i]) {
        return false;
      }
    }
    return true;
  }
Referenced by CryptoLibrary.CryptoLibraryClass.TransformFile().
ComputeHMACSHA1()
byte [] CryptoLibrary.CryptoLibraryClass.ComputeHMACSHA1 (byte[] data, byte[] key)
Computes the HMAC-SHA1 hash of the given data using the provided key.
Parameters
data The data to compute the HMAC-SHA1 hash for.
key The HMAC-SHA1 key.
Returns
The computed HMAC-SHA1 hash.
Definition at line 124 of file CryptoLibrary.cs.
                                                         {
    using (HMACSHA1 hmacSha1 = new HMACSHA1(key)) {
      return hmacSha1.ComputeHash(data);
    }
  }
References CryptoLibrary.CryptoLibraryClass.key.
Referenced by CryptoLibrary.CryptoLibraryClass.HOTP().
ComputeSHA1()
byte [] CryptoLibrary.CryptoLibraryClass.ComputeSHA1 (byte[] data)
Computes the SHA-1 hash of the given data.
Parameters
data The data to compute the hash for.
Returns
The computed SHA-1 hash.
Definition at line 113 of file CryptoLibrary.cs.
                                         {
    using (SHA1 sha1 = SHA1.Create()) {
      return sha1.ComputeHash(data);
    }
  }
Referenced by CryptoLibrary.CryptoLibraryClass.TransformFile().
ComputeSHA256()
byte [] CryptoLibrary.CryptoLibraryClass.ComputeSHA256 (byte[] data)
Computes the SHA-256 hash of the given data.
Parameters
data The data to compute the hash for.
Returns
The computed SHA-256 hash.
Definition at line 134 of file CryptoLibrary.cs.
                                           {
    using (SHA256 sha256 = SHA256.Create()) {
      return sha256.ComputeHash(data);
    }
  }
Referenced by CryptoLibrary.CryptoLibraryClass.TransformFile().
ConvertToBinary()
void CryptoLibrary.CryptoLibraryClass.ConvertToBinary (string inputFile, string outputFile) [private]
Converts the contents of the input file to binary and saves it to the output file.
Parameters
inputFile The path of the input file.
outputFile The path of the output file.
Definition at line 163 of file CryptoLibrary.cs.
                                                                    {
    byte[] buffer;
    using (FileStream fileStream = File.OpenRead(inputFile)) {
      buffer = new byte[fileStream.Length];
      fileStream.Read(buffer, 0, buffer.Length);
    }
    using (FileStream fileStream = File.OpenWrite(outputFile)) {
      fileStream.Write(buffer, 0, buffer.Length);
    }
  }
Referenced by CryptoLibrary.CryptoLibraryClass.TransformFile().
CreateBuffer()
byte [] CryptoLibrary.CryptoLibraryClass.CreateBuffer (byte[] sha1D, byte[] fileData, byte[] sha256D) [private]
Creates a buffer by combining the SHA1 digest, file data, and SHA256 digest.
Parameters
sha1D The SHA1 digest.
fileData The file data.
sha256D The SHA256 digest.
Returns
The combined buffer.
Definition at line 180 of file CryptoLibrary.cs.
                                                                             {
    int bufferLength = 4 + sha1D.Length + fileData.Length + sha256D.Length + BlockSizeInBytes;
    byte[] buffer = new byte[bufferLength];
    Buffer.BlockCopy(BitConverter.GetBytes(fileData.Length), 0, buffer, 0, 4);
    Buffer.BlockCopy(sha1D, 0, buffer, 4, sha1D.Length);
    Buffer.BlockCopy(fileData, 0, buffer, 4 + sha1D.Length, fileData.Length);
    Buffer.BlockCopy(sha256D, 0, buffer, 4 + sha1D.Length + fileData.Length, sha256D.Length);
    return buffer;
  }
References CryptoLibrary.CryptoLibraryClass.BlockSizeInBytes.
Referenced by CryptoLibrary.CryptoLibraryClass.TransformFile().
DecryptData()
byte [] CryptoLibrary.CryptoLibraryClass.DecryptData (byte[] data)
Decrypts the data using AES decryption.
Parameters
data The data to be decrypted.
Returns
The decrypted data.
Definition at line 210 of file CryptoLibrary.cs.
                                         {
    using (System.Security.Cryptography.Aes aes = System.Security.Cryptography.Aes.Create()) {
      aes.Key = key;
      aes.IV = new byte[16];
      aes.Mode = CipherMode.CBC;
      aes.Padding = PaddingMode.PKCS7;
      using (ICryptoTransform decryptor = aes.CreateDecryptor()) {
        return decryptor.TransformFinalBlock(data, 0, data.Length);
      }
    }
  }
References CryptoLibrary.CryptoLibraryClass.key.
Referenced by CryptoLibrary.CryptoLibraryClass.TransformFile().
EncryptData()
byte [] CryptoLibrary.CryptoLibraryClass.EncryptData (byte[] data)
Encrypts the data using AES encryption.
Parameters
data The data to be encrypted.
Returns
The encrypted data.
Definition at line 194 of file CryptoLibrary.cs.
                                         {
    using (Aes aes = Aes.Create()) {
      aes.Key = key;
      aes.IV = new byte[16];
      aes.Mode = CipherMode.CBC;
      aes.Padding = PaddingMode.PKCS7;
      using (ICryptoTransform encryptor = aes.CreateEncryptor()) {
        return encryptor.TransformFinalBlock(data, 0, data.Length);
      }
    }
  }
References CryptoLibrary.CryptoLibraryClass.key.
Referenced by CryptoLibrary.CryptoLibraryClass.TransformFile().
GetPasswordFromDigest()
int CryptoLibrary.CryptoLibraryClass.GetPasswordFromDigest (byte[] digest) [private]
Gets the password from the SHA256 digest.
Parameters
digest The SHA256 digest.
Returns
The password as an integer.
Definition at line 226 of file CryptoLibrary.cs.
                                                   {
    return BitConverter.ToInt32(digest, 0);
  }
Referenced by CryptoLibrary.CryptoLibraryClass.TransformFile().
HOTP()
int CryptoLibrary.CryptoLibraryClass.HOTP (byte[] key, int counter)
Calculates the HOTP (HMAC-based One-Time Password) value based on the specified key and counter.
Parameters
key The HMAC key.
counter The counter value.
Returns
The calculated HOTP value.
Definition at line 88 of file CryptoLibrary.cs.
                                           {
    CryptoLibraryClass crypto = new CryptoLibraryClass(key);
    byte[] hmacBytes = crypto.ComputeHMACSHA1(key, BitConverter.GetBytes(counter));
    int sbits = CalculateDynamicTruncation(hmacBytes);
    int hotpValue = (int)(sbits % 1000000);
    return hotpValue;
  }
References CryptoLibrary.CryptoLibraryClass.CalculateDynamicTruncation(), CryptoLibrary.CryptoLibraryClass.ComputeHMACSHA1(), CryptoLibrary.CryptoLibraryClass.CryptoLibraryClass(), and CryptoLibrary.CryptoLibraryClass.key.
TransformFile()
int CryptoLibrary.CryptoLibraryClass.TransformFile (string sourceFilePath, string destFilePath, int operation)
Transforms a file based on the specified operation.
Parameters
sourceFilePath The path of the source file.
destFilePath The path of the destination file.
operation The operation to perform. 0 for decryption, 1 for encryption.
Returns
If operation is 1, returns the password obtained from the SHA256 digest. Otherwise, returns 0.
Exceptions
ArgumentException Thrown when an invalid operation is specified.
Definition at line 42 of file CryptoLibrary.cs.
                                                                                      {
    CryptoLibraryClass crypto = new CryptoLibraryClass(key);
    string newsourceFilePath = "Hello.bin";
    crypto.ConvertToBinary(sourceFilePath, newsourceFilePath);
    if (operation == 1) {
      byte[] fileData = File.ReadAllBytes(newsourceFilePath);
      byte[] sha1D = crypto.ComputeSHA1(fileData);
      byte[] sha256D = crypto.ComputeSHA256(fileData);
      byte[] buffer = crypto.CreateBuffer(sha1D, fileData, sha256D);
      byte[] encryptedBuffer = crypto.EncryptData(buffer);
      File.WriteAllBytes(destFilePath, encryptedBuffer);
      return crypto.GetPasswordFromDigest(encryptedBuffer);
    } else if (operation == 0) {
      byte[] encryptedBuffer = File.ReadAllBytes(sourceFilePath);
      byte[] decryptedData = crypto.DecryptData(encryptedBuffer);
      int length = BitConverter.ToInt32(decryptedData, 0);
      int sha1D_Offset = 4;
      int fileData_Offset = 24;
      int sha256D_Offset = 24 + length;
      byte[] sha1D = new byte[20];
      Buffer.BlockCopy(decryptedData, sha1D_Offset, sha1D, 0, 20);
      byte[] fileData = new byte[length];
      Buffer.BlockCopy(decryptedData, fileData_Offset, fileData, 0, length);
      byte[] sha256D = new byte[32];
      Buffer.BlockCopy(decryptedData, sha256D_Offset, sha256D, 0, 32);
      byte[] calsha1D = crypto.ComputeSHA1(fileData);
      byte[] calsha256D = crypto.ComputeSHA256(fileData);
      bool sha1Val = crypto.CompareHashes(sha1D, calsha1D);
      bool sha256Val = crypto.CompareHashes(sha256D, calsha256D);
      if (sha1Val && sha256Val) {
        File.WriteAllBytes(destFilePath, fileData);
      }
      return 0;
    } else {
      throw new ArgumentException("Invalid operation specified. Operation must be 0 or 1.");
    }
  }
References CryptoLibrary.CryptoLibraryClass.CompareHashes(), CryptoLibrary.CryptoLibraryClass.ComputeSHA1(), CryptoLibrary.CryptoLibraryClass.ComputeSHA256(), CryptoLibrary.CryptoLibraryClass.ConvertToBinary(), CryptoLibrary.CryptoLibraryClass.CreateBuffer(), CryptoLibrary.CryptoLibraryClass.CryptoLibraryClass(), CryptoLibrary.CryptoLibraryClass.DecryptData(), CryptoLibrary.CryptoLibraryClass.EncryptData(), CryptoLibrary.CryptoLibraryClass.GetPasswordFromDigest(), and CryptoLibrary.CryptoLibraryClass.key.
Member Data Documentation
BlockSizeInBytes
const int CryptoLibrary.CryptoLibraryClass.BlockSizeInBytes = 16 [static], [private]
The size of the encryption block in bytes.
Definition at line 16 of file CryptoLibrary.cs.
Referenced by CryptoLibrary.CryptoLibraryClass.CreateBuffer().
key
readonly byte [] CryptoLibrary.CryptoLibraryClass.key [private]
The encryption key.
Definition at line 20 of file CryptoLibrary.cs.
Referenced by CryptoLibrary.CryptoLibraryClass.ComputeHMACSHA1(), CryptoLibrary.CryptoLibraryClass.CryptoLibraryClass(), CryptoLibrary.CryptoLibraryClass.DecryptData(), CryptoLibrary.CryptoLibraryClass.EncryptData(), CryptoLibrary.CryptoLibraryClass.HOTP(), and CryptoLibrary.CryptoLibraryClass.TransformFile().
KeySizeInBytes
const int CryptoLibrary.CryptoLibraryClass.KeySizeInBytes = 16 [static], [private]
The size of the encryption key in bytes.
Definition at line 12 of file CryptoLibrary.cs.
Referenced by CryptoLibrary.CryptoLibraryClass.CryptoLibraryClass().
The documentation for this class was generated from the following file:
CryptoLibrary/CryptoLibrary.cs